#!/bin/bash
set -e
eval ` eldk-switch.sh -r 5.4 armv7a`
# PATH=$PATH:/opt/eldk-4.2-2008-11-24/usr/bin/
D=`git describe`
TFTP=/srv/tftp
#CROSS_COMPILE="ccache $CROSS_COMPILE"
DT="omap3-n950"
# uImage LOADADDR=0x80008000
ARCH=arm long make -j 5 zImage && \
    ARCH=arm make $DT.dtb && \
    cat arch/arm/boot/zImage arch/arm/boot/dts/$DT.dtb > arch/arm/boot/zImage-dtb && \
    echo done

# Run is dangerous -- often needs to be done twice.
#    ./run_nfsroot_950

