#!/bin/bash
eval ` eldk-switch.sh -r 5.4 armv7a`
set -e
# PATH=$PATH:/opt/eldk-4.2-2008-11-24/usr/bin/
D=`git describe`
TFTP=/srv/tftp
# uImage LOADADDR=0x80008000
#CROSS_COMPILE="ccache $CROSS_COMPILE"
echo "Cross compile: $CROSS_COMPILE"
ARCH=arm long make -j 5 zImage
    ARCH=arm make omap3-n900.dtb
    cat arch/arm/boot/zImage arch/arm/boot/dts/omap3-n900.dtb > arch/arm/boot/zImage-dtb
    ARCH=arm nice make -j 3 modules
    ../maemo/run_hw
    
#    cp drivers/bluetooth/nokia_h4p.ko drivers/tty/serial/*.ko drivers/media/i2c/adp1653.ko /srv/nfs/n900/my/modules/
