#!/bin/bash
# Chce to nabootovat debiani jadro na PC!
# ..a nebo aspon neco s podporou nfs.
IMG=zImage-dtb
#IMG=zImage-dtb810
sudo ../maemo/0xffff/src/0xFFFF -l -m kernel:arch/arm/boot/$IMG -b
#-m initfs:/tmp/postmarketOS-export/initramfs-nokia-n9
# -l -b 'console=ttyS2,115200 console=tty0 earlyprintk earlycon g_ether.host_addr=00:00:00:00:23:42 root=/dev/mmcblk0p3 rootwait rw'

# single
# init=/my/init

sleep 25
sudo ifconfig eth3 192.168.1.6 up
sleep 65
issh -X user@usb
