#!/bin/bash
# Chce to nabootovat debiani jadro na PC!
# ..a nebo aspon neco s podporou nfs.
IMG=zImage-dtb
#IMG=zImage-dtb810
sudo ../maemo/0xffff/src/0xFFFF -m kernel:arch/arm/boot/$IMG -l -b 'console=ttyS2,115200 console=tty0 earlyprintk earlycon g_ether.host_addr=00:00:00:00:23:42 root=/dev/mmcblk0p3 rootwait rw'

# single
# init=/my/init

sleep 15
sudo ifconfig usb0 192.168.1.6 netmask 255.255.255.252
sleep 1
sudo route add 192.168.1.8 dev usb0

sleep 130
ssh -X root@usb

# echo 1 > /proc/sys/net/ipv4/ip_forward
# 

# iw wlan0 connect pavel
# ifconfig wlan0 10.0.0.8 up
# 

fix_wifi_duo () {
 sudo route del default
 sudo route del 10.0.0.251 dev usb0
 sudo route add default gw 10.0.0.251
}
